#!/usr/bin/env bash
# Sync project-local AI tooling from templates and stack packs.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

REPO_ROOT="$(repo_root)"
DETECT_STACK="${REPO_ROOT}/scripts/detect-project-stack.sh"

PROJECT=""
TOOL="all"
AUTO_DETECT=0
DRY_RUN=0
STACKS=""

usage() {
  cat <<'EOF'
Usage: sync-project-tooling.sh --project <path> [options]

Options:
  --project <path>       Target project directory (required)
  --tool <name>          claude | cursor | codex | all (default: all)
  --auto-detect          Detect stacks from project filesystem
  --stack <a,b,c>        Comma-separated stacks (node,scala,python,go,java,dotnet,clojure,terraform)
  --dry-run              Show actions without writing files
  -h, --help             Show help

Examples:
  ./scripts/sync-project-tooling.sh --project ~/work/foo --tool all --auto-detect --dry-run
  ./scripts/sync-project-tooling.sh --project ~/work/foo --tool claude --stack node,terraform
EOF
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --project) PROJECT="$2"; shift 2 ;;
      --tool) TOOL="$2"; shift 2 ;;
      --auto-detect) AUTO_DETECT=1; shift ;;
      --stack) STACKS="$2"; shift 2 ;;
      --dry-run) DRY_RUN=1; shift ;;
      -h|--help) usage; exit 0 ;;
      *) log_fail "unknown argument: $1"; usage >&2; exit 2 ;;
    esac
  done
}

resolve_stacks() {
  SELECTED_STACKS=()

  if [[ -n "$STACKS" ]]; then
    IFS=',' read -ra SELECTED_STACKS <<< "$STACKS"
  elif [[ "$AUTO_DETECT" -eq 1 ]]; then
    SELECTED_STACKS=()
    while IFS= read -r line; do
      [[ -n "$line" ]] && SELECTED_STACKS+=("$line")
    done < <("$DETECT_STACK" "$PROJECT" 2>/dev/null || true)
  fi
}

compose_markdown() {
  local output="$1"
  shift
  local parts=("$@")

  if [[ "$DRY_RUN" -eq 1 ]]; then
    log_info "[dry-run] would compose ${output} from ${#parts[@]} part(s)"
    return 0
  fi

  if [[ -f "$output" ]]; then
    local backup="${output}.backup-$(timestamp)"
    cp -a "$output" "$backup"
    log_info "backup created: ${backup}"
  fi

  {
    echo "<!-- Generated by dev-ai-tooling sync-project-tooling.sh -->"
    echo "<!-- Do not edit blindly; customize for this project. -->"
    echo
    for part in "${parts[@]}"; do
      [[ -f "$part" ]] || continue
      cat "$part"
      echo
      echo "---"
      echo
    done
  } > "$output"
  log_ok "composed: ${output}"
}

sync_claude() {
  local claude_dir="${PROJECT}/.claude"
  ensure_dir "$claude_dir"

  compose_markdown "${claude_dir}/CLAUDE.md" \
    "${REPO_ROOT}/templates/project/base/CLAUDE.md" \
    $(for s in "${SELECTED_STACKS[@]}"; do echo "${REPO_ROOT}/stacks/${s}/CLAUDE.md"; done)

  if [[ -d "${REPO_ROOT}/claude/hooks" ]]; then
    if [[ "$DRY_RUN" -eq 1 ]]; then
      log_info "[dry-run] would copy hooks to ${claude_dir}/hooks"
    else
      ensure_dir "${claude_dir}/hooks"
      for hook in "${REPO_ROOT}/claude/hooks/"*.sh; do
        [[ -f "$hook" ]] || continue
        local dest="${claude_dir}/hooks/$(basename "$hook")"
        copy_with_backup "$hook" "$dest"
        chmod +x "$dest"
      done
    fi
  fi

  log_info "Claude project sync complete (skills/agents remain project-specific; add manually if needed)"
}

sync_cursor() {
  local cursor_dir="${PROJECT}/.cursor"
  ensure_dir "$cursor_dir"

  if [[ -d "${REPO_ROOT}/cursor/rules" ]]; then
    if [[ "$DRY_RUN" -eq 1 ]]; then
      log_info "[dry-run] would copy cursor/rules to ${cursor_dir}/rules"
    else
      ensure_dir "${cursor_dir}/rules"
      shopt -s nullglob
      for rule in "${REPO_ROOT}/cursor/rules/"*; do
        [[ -e "$rule" ]] || continue
        copy_with_backup "$rule" "${cursor_dir}/rules/$(basename "$rule")"
      done
      shopt -u nullglob
    fi
  fi

  if [[ -d "${REPO_ROOT}/claude/hooks" ]]; then
    if [[ "$DRY_RUN" -eq 1 ]]; then
      log_info "[dry-run] would copy hooks to ${cursor_dir}/hooks (from claude/hooks implementations)"
    else
      ensure_dir "${cursor_dir}/hooks"
      for hook in "${REPO_ROOT}/claude/hooks/"*.sh; do
        [[ -f "$hook" ]] || continue
        local dest="${cursor_dir}/hooks/$(basename "$hook")"
        copy_with_backup "$hook" "$dest"
        chmod +x "$dest"
      done
    fi
  fi

  log_info "Cursor project sync complete"
}

sync_codex() {
  compose_markdown "${PROJECT}/AGENTS.md" \
    "${REPO_ROOT}/templates/project/base/AGENTS.md" \
    $(for s in "${SELECTED_STACKS[@]}"; do echo "${REPO_ROOT}/stacks/${s}/AGENTS.md"; done)
}

sync_shared() {
  copy_with_backup \
    "${REPO_ROOT}/templates/project/base/AI_WORKFLOW.md" \
    "${PROJECT}/AI_WORKFLOW.md"
}

parse_args "$@"

if [[ -z "$PROJECT" ]]; then
  log_fail "--project is required"
  usage >&2
  exit 2
fi

PROJECT="$(cd "$PROJECT" && pwd)"
export DRY_RUN

log_info "Syncing tooling to: ${PROJECT}"
log_info "Tool: ${TOOL} | auto-detect: ${AUTO_DETECT} | dry-run: ${DRY_RUN}"

resolve_stacks

if ((${#SELECTED_STACKS[@]} > 0)); then
  log_info "Stacks: ${SELECTED_STACKS[*]}"
else
  log_warn "No stacks selected; only base templates will be applied"
fi

case "$TOOL" in
  claude)
    sync_claude
    ;;
  cursor)
    sync_cursor
    ;;
  codex)
    sync_codex
    sync_shared
    ;;
  all)
    sync_claude
    sync_cursor
    sync_codex
    sync_shared
    ;;
  *)
    log_fail "invalid --tool value: ${TOOL}"
    exit 2
    ;;
esac

log_ok "Done."
